In [89]:
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from operator import sub
output_notebook()

Loading BokehJS ...

In [90]:
# Grid World
class Agent(object):
    def __init__(self):
        self.rules = {'w':(0, -1), 'd':(1, 0), 's':(0, 1), 'a':(-1, 0)}
        self.pos = (0, 0)
        
    def move(self, x):
        # return: reward, terminal
        pos_ = self.pos
        self.pos = tuple(map(sub, self.pos, self.rules[x]))
        if self.pos[0] < 0 or self.pos[0] > 3 or self.pos[1] < 0 or self.pos[1] > 3:
            self.pos = pos_
            return -1, 0
        if self.pos == (0, 0) or self.pos == (3, 3):
            return -1, 1
        return -1, 0

In [91]:
actions = ['w', 's', 'a', 'd']
gamma = 1.0
agent = Agent()

In [92]:
# Iterative Policy Evaluation: Random Policy
v = np.zeros((4, 4))
epoch = 0
while True:
    tmp = v.copy()
    for i in range(4):
        for j in range(4):
            if (i, j) == (0, 0) or (i, j) == (3, 3):
                continue
            v_ = []
            for act in actions:
                agent.pos = (i, j)
                r, _ = agent.move(act)
                x_, y_ = agent.pos
                v_.append((r + gamma * tmp[x_, y_]))
            v[i, j] = np.mean(v_)
    epoch += 1
    if np.sum(np.abs(v - tmp)) < 0.001:
        break
print v.transpose()
print np.sum(np.abs(v - tmp)), epoch

[[  0.         -13.99909918 -19.99866515 -21.99850623]
 [-13.99909918 -17.99882408 -19.99867408 -19.99866515]
 [-19.99866515 -19.99867408 -17.99882408 -13.99909918]
 [-21.99850623 -19.99866515 -13.99909918   0.        ]]
0.000951429590359 176


In [65]:
# Policy Iteration, Jack's Car
v = np.zeros((20, 20))
actions = range(-5, 6)
epoch = 0
while True:
    tmp = v.copy()
    for i in range(4):
        for j in range(4):
            v_ = []
            for act in actions:
                pos = (i, j)
                pos_ = (i+act, j-act)
                if any(xx < 0 or x > 20 for xx in pos_):
                    continue
                r = 
                x_, y_ = agent.pos
                v_.append((r + gamma * tmp[x_, y_]))
            v[i, j] = np.mean(v_)
    epoch += 1
    if np.sum(np.abs(v - tmp)) < 0.001:
        break

In [66]:
np.sum(v)

0.0

In [78]:
range(-5, 5)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]

In [82]:
any((3, 4) > 3)

TypeError: 'bool' object is not iterable

In [85]:
any(list((3, 4)) > 3)

TypeError: 'bool' object is not iterable

In [88]:
any(x < 3 for x in (3, 4, 5))

False