In [114]:
import numpy as np
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from operator import sub
output_notebook()

Loading BokehJS ...

In [115]:
class Agent(object):
    def __init__(self):
        self.rules = {'w':(0, -1), 'd':(1, 0), 's':(0, 1), 'a':(-1, 0)}
        self.pos = (0, 0)
        
    def move(self, x):
        if self.pos == (1, 0):
            self.pos = (1, 4)
            return 10
        if self.pos == (3, 0):
            self.pos = (3, 2)
            return 5
        
        pos_ = self.pos
        self.pos = tuple(map(sub, self.pos, self.rules[x]))
        if self.pos[0] < 0 or self.pos[0] > 4 or self.pos[1] < 0 or self.pos[1] > 4:
            self.pos = pos_
            return -1
        return 0        

In [116]:
actions = ['w', 's', 'a', 'd']
gamma = 0.9
agent = Agent()

In [120]:
# Bellman Equation
v = np.zeros((5, 5))
for epoch in range(100):
    for i in range(5):
        for j in range(5):
            v_ = 0
            for act in actions:
                agent.pos = (i, j)
                r = agent.move(act)
                x_, y_ = agent.pos
                v_ += (r + gamma * v[x_, y_])
            v[i, j] = v_ / 4
print v.transpose()

[[ 3.30899635  8.78929187  4.42761919  5.3223676   1.49217877]
 [ 1.52158808  2.99231787  2.25013996  1.90757171  0.54740272]
 [ 0.0508225   0.7381706   0.67311327  0.35818622 -0.40314113]
 [-0.97359229 -0.43549542 -0.35488226 -0.58560508 -1.18307507]
 [-1.85770054 -1.34523125 -1.22926725 -1.42291814 -1.97517904]]


In [121]:
p = figure(x_range=[0, 5], y_range=[0, 5])
p.image(image=[np.rot90(v)], x=[0], y=[0], dw=[5], dh=[5], palette="Spectral11")
show(p)

In [101]:
print v.transpose()

[[ 3.30899635  8.78929187  4.42761919  5.3223676   1.49217877]
 [ 1.52158808  2.99231787  2.25013996  1.90757171  0.54740272]
 [ 0.0508225   0.7381706   0.67311327  0.35818622 -0.40314113]
 [-0.97359229 -0.43549542 -0.35488226 -0.58560508 -1.18307507]
 [-1.85770054 -1.34523125 -1.22926725 -1.42291814 -1.97517904]]


In [122]:
# Optimal Value Functions
v = np.zeros((5, 5))
for epoch in range(100):
    for i in range(5):
        for j in range(5):
            v_ = []
            for act in actions:
                agent.pos = (i, j)
                r = agent.move(act)
                x_, y_ = agent.pos
                v_.append((r + gamma * v[x_, y_]))
            v[i, j] = max(v_)
print v.transpose()

[[ 21.97748529  24.4194281   21.97748529  19.4194281   17.47748529]
 [ 19.77973676  21.97748529  19.77973676  17.80176308  16.02158677]
 [ 17.80176308  19.77973676  17.80176308  16.02158677  14.4194281 ]
 [ 16.02158677  17.80176308  16.02158677  14.4194281   12.97748529]
 [ 14.4194281   16.02158677  14.4194281   12.97748529  11.67973676]]


In [123]:
p = figure(x_range=[0, 5], y_range=[0, 5])
p.image(image=[np.rot90(v)], x=[0], y=[0], dw=[5], dh=[5], palette="Spectral11")
show(p)